In [1]:
# Importing necessary libraries
import pandas as pd  # For data manipulation and analysis
import numpy as np  # For numerical computations
import matplotlib.pyplot as plt  # For data visualization
import seaborn as sns  # For advanced data visualization
from scipy import stats  # For statistical analysis

# Enable inline plotting for Jupyter Notebook
%matplotlib inline

In [2]:
# Reading the dataset file
dataset = pd.read_csv('dataset.csv')  # Replace 'your_dataset_file.csv' with the actual file name

# Display the first few rows of the dataset
dataset.head()

,Gender,Age,NS1,IgG,IgM,Area,AreaType,HouseType,District,Outcome
0,Female,45,0,0,0,Mirpur,Undeveloped,Building,Dhaka,0
1,Male,17,0,0,1,Chawkbazar,Developed,Building,Dhaka,0
2,Female,29,0,0,0,Paltan,Undeveloped,Other,Dhaka,0
3,Female,63,1,1,0,Motijheel,Developed,Other,Dhaka,1
4,Male,22,0,0,0,Gendaria,Undeveloped,Building,Dhaka,0

In [3]:
dataset.tail()

,Gender,Age,NS1,IgG,IgM,Area,AreaType,HouseType,District,Outcome
995,Female,16,1,1,0,New Market,Developed,Building,Dhaka,1
996,Male,41,1,1,0,Paltan,Undeveloped,Other,Dhaka,1
997,Male,45,0,0,1,Motijheel,Developed,Building,Dhaka,0
998,Female,19,1,1,1,Paltan,Undeveloped,Building,Dhaka,1
999,Female,28,0,0,1,Adabor,Developed,Building,Dhaka,0

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Gender     1000 non-null   object
 1   Age        1000 non-null   int64
 2   NS1        1000 non-null   int64
 3   IgG        1000 non-null   int64
 4   IgM        1000 non-null   int64
 5   Area       1000 non-null   object
 6   AreaType   1000 non-null   object
 7   HouseType  1000 non-null   object
 8   District   1000 non-null   object
 9   Outcome    1000 non-null   int64
dtypes: int64(5), object(5)
memory usage: 78.3+ KB

In [5]:
dataset.describe()

               Age          NS1          IgG          IgM      Outcome
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000
mean     35.924000     0.519000     0.533000     0.475000     0.533000
std      16.468437     0.499889     0.499159     0.499624     0.499159
min       8.000000     0.000000     0.000000     0.000000     0.000000
25%      22.000000     0.000000     0.000000     0.000000     0.000000
50%      37.000000     1.000000     1.000000     0.000000     1.000000
75%      50.000000     1.000000     1.000000     1.000000     1.000000
max      65.000000     1.000000     1.000000     1.000000     1.000000